services:
  postgres:
    image: postgres:16
    container_name: weather_energy_postgres
    environment:
      POSTGRES_DB: weather_energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
